export type GuideCity = { slug: string; city: string; county: "Broward" | "Miami-Dade" | "Palm Beach" };

export const GUIDE_CITIES: GuideCity[] = [
  { slug: "unincorporated-palm-beach", city: "Unincorporated Palm Beach County", county: "Palm Beach" },
  { slug: "atlantis", city: "Atlantis", county: "Palm Beach" },
  { slug: "belle-glade", city: "Belle Glade", county: "Palm Beach" },
  { slug: "boca-raton", city: "Boca Raton", county: "Palm Beach" },
  { slug: "boynton-beach", city: "Boynton Beach", county: "Palm Beach" },
  { slug: "briny-breezes", city: "Briny Breezes", county: "Palm Beach" },
  { slug: "cloud-lake", city: "Cloud Lake", county: "Palm Beach" },
  { slug: "delray-beach", city: "Delray Beach", county: "Palm Beach" },
  { slug: "glen-ridge", city: "Glen Ridge", county: "Palm Beach" },
  { slug: "gulf-stream", city: "Gulf Stream", county: "Palm Beach" },
  { slug: "greenacres", city: "Greenacres", county: "Palm Beach" },
  { slug: "haverhill", city: "Haverhill", county: "Palm Beach" },
  { slug: "highland-beach", city: "Highland Beach", county: "Palm Beach" },
  { slug: "hypoluxo", city: "Hypoluxo", county: "Palm Beach" },
  { slug: "juno-beach", city: "Juno Beach", county: "Palm Beach" },
  { slug: "jupiter", city: "Jupiter", county: "Palm Beach" },
  { slug: "jupiter-inlet-colony", city: "Jupiter Inlet Colony", county: "Palm Beach" },
  { slug: "lake-clarke-shores", city: "Lake Clarke Shores", county: "Palm Beach" },
  { slug: "lake-park", city: "Lake Park", county: "Palm Beach" },
  { slug: "lake-worth-beach", city: "Lake Worth Beach", county: "Palm Beach" },
  { slug: "lantana", city: "Lantana", county: "Palm Beach" },
  { slug: "loxahatchee-groves", city: "Loxahatchee Groves", county: "Palm Beach" },
  { slug: "manalapan", city: "Manalapan", county: "Palm Beach" },
  { slug: "mangonia-park", city: "Mangonia Park", county: "Palm Beach" },
  { slug: "north-palm-beach", city: "North Palm Beach", county: "Palm Beach" },
  { slug: "ocean-ridge", city: "Ocean Ridge", county: "Palm Beach" },
  { slug: "pahokee", city: "Pahokee", county: "Palm Beach" },
  { slug: "town-of-palm-beach", city: "Town of Palm Beach", county: "Palm Beach" },
  { slug: "palm-beach-gardens", city: "Palm Beach Gardens", county: "Palm Beach" },
  { slug: "palm-beach-shores", city: "Palm Beach Shores", county: "Palm Beach" },
  { slug: "palm-springs", city: "Palm Springs", county: "Palm Beach" },
  { slug: "riviera-beach", city: "Riviera Beach", county: "Palm Beach" },
  { slug: "royal-palm-beach", city: "Royal Palm Beach", county: "Palm Beach" },
  { slug: "south-bay", city: "South Bay", county: "Palm Beach" },
  { slug: "south-palm-beach", city: "South Palm Beach", county: "Palm Beach" },
  { slug: "tequesta", city: "Tequesta", county: "Palm Beach" },
  { slug: "wellington", city: "Wellington", county: "Palm Beach" },
  { slug: "westlake", city: "Westlake", county: "Palm Beach" },
  { slug: "west-palm-beach", city: "West Palm Beach", county: "Palm Beach" },
  { slug: "unincorporated-broward", city: "Unincorporated Broward County", county: "Broward" },
  { slug: "coconut-creek", city: "Coconut Creek", county: "Broward" },
  { slug: "cooper-city", city: "Cooper City", county: "Broward" },
  { slug: "coral-springs", city: "Coral Springs", county: "Broward" },
  { slug: "dania-beach", city: "Dania Beach", county: "Broward" },
  { slug: "davie", city: "Davie", county: "Broward" },
  { slug: "deerfield-beach", city: "Deerfield Beach", county: "Broward" },
  { slug: "fort-lauderdale", city: "Fort Lauderdale", county: "Broward" },
  { slug: "hallandale-beach", city: "Hallandale Beach", county: "Broward" },
  { slug: "hillsboro-beach", city: "Hillsboro Beach", county: "Broward" },
  { slug: "hollywood", city: "Hollywood", county: "Broward" },
  { slug: "lauderdale-by-the-sea", city: "Lauderdale-by-the-Sea", county: "Broward" },
  { slug: "lauderdale-lakes", city: "Lauderdale Lakes", county: "Broward" },
  { slug: "lauderhill", city: "Lauderhill", county: "Broward" },
  { slug: "lazy-lake", city: "Lazy Lake", county: "Broward" },
  { slug: "lighthouse-point", city: "Lighthouse Point", county: "Broward" },
  { slug: "margate", city: "Margate", county: "Broward" },
  { slug: "miramar", city: "Miramar", county: "Broward" },
  { slug: "north-lauderdale", city: "North Lauderdale", county: "Broward" },
  { slug: "oakland-park", city: "Oakland Park", county: "Broward" },
  { slug: "parkland", city: "Parkland", county: "Broward" },
  { slug: "pembroke-park", city: "Pembroke Park", county: "Broward" },
  { slug: "pembroke-pines", city: "Pembroke Pines", county: "Broward" },
  { slug: "plantation", city: "Plantation", county: "Broward" },
  { slug: "pompano-beach", city: "Pompano Beach", county: "Broward" },
  { slug: "sea-ranch-lakes", city: "Sea Ranch Lakes", county: "Broward" },
  { slug: "southwest-ranches", city: "Southwest Ranches", county: "Broward" },
  { slug: "sunrise", city: "Sunrise", county: "Broward" },
  { slug: "tamarac", city: "Tamarac", county: "Broward" },
  { slug: "west-park", city: "West Park", county: "Broward" },
  { slug: "weston", city: "Weston", county: "Broward" },
  { slug: "wilton-manors", city: "Wilton Manors", county: "Broward" },
  { slug: "unincorporated-miami-dade", city: "Unincorporated Miami-Dade County", county: "Miami-Dade" },
  { slug: "aventura", city: "Aventura", county: "Miami-Dade" },
  { slug: "bal-harbour", city: "Bal Harbour", county: "Miami-Dade" },
  { slug: "bay-harbor-islands", city: "Bay Harbor Islands", county: "Miami-Dade" },
  { slug: "biscayne-park", city: "Biscayne Park", county: "Miami-Dade" },
  { slug: "coral-gables", city: "Coral Gables", county: "Miami-Dade" },
  { slug: "cutler-bay", city: "Cutler Bay", county: "Miami-Dade" },
  { slug: "doral", city: "Doral", county: "Miami-Dade" },
  { slug: "el-portal", city: "El Portal", county: "Miami-Dade" },
  { slug: "florida-city", city: "Florida City", county: "Miami-Dade" },
  { slug: "golden-beach", city: "Golden Beach", county: "Miami-Dade" },
  { slug: "hialeah", city: "Hialeah", county: "Miami-Dade" },
  { slug: "hialeah-gardens", city: "Hialeah Gardens", county: "Miami-Dade" },
  { slug: "homestead", city: "Homestead", county: "Miami-Dade" },
  { slug: "indian-creek", city: "Indian Creek", county: "Miami-Dade" },
  { slug: "key-biscayne", city: "Key Biscayne", county: "Miami-Dade" },
  { slug: "medley", city: "Medley", county: "Miami-Dade" },
  { slug: "miami", city: "Miami", county: "Miami-Dade" },
  { slug: "miami-beach", city: "Miami Beach", county: "Miami-Dade" },
  { slug: "miami-gardens", city: "Miami Gardens", county: "Miami-Dade" },
  { slug: "miami-lakes", city: "Miami Lakes", county: "Miami-Dade" },
  { slug: "miami-shores", city: "Miami Shores", county: "Miami-Dade" },
  { slug: "miami-springs", city: "Miami Springs", county: "Miami-Dade" },
  { slug: "north-bay-village", city: "North Bay Village", county: "Miami-Dade" },
  { slug: "north-miami", city: "North Miami", county: "Miami-Dade" },
  { slug: "north-miami-beach", city: "North Miami Beach", county: "Miami-Dade" },
  { slug: "opa-locka", city: "Opa-locka", county: "Miami-Dade" },
  { slug: "palmetto-bay", city: "Palmetto Bay", county: "Miami-Dade" },
  { slug: "pinecrest", city: "Pinecrest", county: "Miami-Dade" },
  { slug: "south-miami", city: "South Miami", county: "Miami-Dade" },
  { slug: "sunny-isles-beach", city: "Sunny Isles Beach", county: "Miami-Dade" },
  { slug: "surfside", city: "Surfside", county: "Miami-Dade" },
  { slug: "sweetwater", city: "Sweetwater", county: "Miami-Dade" },
  { slug: "virginia-gardens", city: "Virginia Gardens", county: "Miami-Dade" },
  { slug: "west-miami", city: "West Miami", county: "Miami-Dade" },
];
